### ISSUE TITLE
out of bounds exception

### ISSUE THREAD

**Issue by daus-s** [daus-s/wordle#3]
replicable by : 
./wordle
{
enter word: panda
values gyb: bbbbb
...
enter word: gruel
values gyb: yybgb
...
enter word: tiger
values gyb: ybygy
}

I believe it is trying to remove index zero of a zero long array. will debug

**Comment by daus-s** [comment]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at CandidateWords.getInput(CandidateWords.java:133)
	at CandidateWords.main(CandidateWords.java:165)

**Comment by daus-s** [comment]
That's exactly what the error means/says. However, for some reason a word that should not be removed is removed changing the length of the array from 1 to 0 when the answer should be revealed. However, one must consider that it is possible to have 1 remaining word and not come across this error. That means a specific error is occurring in a removal process, in which a "innocent" word is removed. 

Edit: I will do further investigation to determine what kinds of removals are erring. It is likely a problem in code structure rather than algorithm.

**Comment by daus-s** [comment]
this was fixed with todays updates by separating 2 of the checks such that the j is only incremented or decremented in one place per loop with variable j. valid words are not removed now, as y was getting reassigned too early meaning that the letters would overwrite the other positions in the position and misletter arrays.
